/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacadstro2.telas;

import java.time.DayOfWeek;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import sistemacadstro2.entities.Aluno;
import sistemacadstro2.services.Servico;

/**
 *
 * @author lucas
 */
public class DetalhesAluno extends javax.swing.JFrame {

    Aluno aluno;
    Servico service;

    /**
     * Creates new form DetalhesAluno
     */
    public String verificarPermissao(boolean x) {
        if (x) {
            return "Sim";
        } else {
            return "Não";
        }
    }

    public DetalhesAluno(Aluno aluno, Servico service) {
        initComponents();
        this.aluno = aluno;
        this.service = service;

        ArrayList<String> diasS = new ArrayList<>();
        ArrayList<DayOfWeek> doAluno = aluno.getDiasSemana();
        if (doAluno.contains(DayOfWeek.MONDAY)) {
            diasS.add("Segunda");
        }
        if (doAluno.contains(DayOfWeek.TUESDAY)) {
            diasS.add("Terça");
        }
        if (doAluno.contains(DayOfWeek.WEDNESDAY)) {
            diasS.add("Quarta");
        }
        if (doAluno.contains(DayOfWeek.THURSDAY)) {
            diasS.add("Quinta");
        }
        if (doAluno.contains(DayOfWeek.FRIDAY)) {
            diasS.add("Sexta");
        }

        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM");
        nome.setText(aluno.getName());
        peso.setText(String.valueOf(aluno.getPeso()));
        telefone.setText(aluno.getNum_contato());
        idade.setText(String.valueOf(aluno.getIdade()));
        faltas.setText(String.valueOf(aluno.getFaltas()));
        niver.setText(aluno.getAniversario().format(fmt));
        responsavel.setText(aluno.getNome_responsavel());
        email.setText(aluno.getEmail());
        escola.setText(aluno.getEscola());
        medicamento.setText(aluno.getMedicamento_cotinuo());
        observacao.setText(aluno.getObservacao());
        endereco.setText(aluno.getEndereco());
        bairro.setText(aluno.getBairro());
        CEP.setText(aluno.getCep());
        roupa.setText(aluno.getTamanho_roupa());
        calcado.setText(aluno.getTamanho_calcado());
        categora.setText(aluno.getCategoria());
        grau.setText(String.valueOf(aluno.getGrau()));
        faixa.setText(aluno.getFaixa());
        dias.setText(diasS.toString());
        
        ativo.setText(verificarPermissao(aluno.getAtivo()));
        treinar.setText(verificarPermissao(aluno.getAutorizacao_treino()));
        competir.setText(verificarPermissao(aluno.getAutorizacao_competicao()));
        imagear.setText(verificarPermissao(aluno.getAutorizacao_imagem()));

    }

    public DetalhesAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        faltas = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        niver = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        responsavel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bairro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CEP = new javax.swing.JLabel();
        escola = new javax.swing.JLabel();
        observacao = new javax.swing.JLabel();
        calcado = new javax.swing.JLabel();
        roupa = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        faixa = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        categora = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        grau = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        medicamento = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        treinar = new javax.swing.JLabel();
        competir = new javax.swing.JLabel();
        imagear = new javax.swing.JLabel();
        ativo = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        dias = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 59, -1));

        peso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        peso.setText("Peso:");
        getContentPane().add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 81, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Peso:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 59, -1));

        telefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefone.setText("Telefone:");
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 290, -1));

        nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome.setText("Nome:");
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        idade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idade.setText("Idade: ");
        getContentPane().add(idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 290, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Idade: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 64, -1));

        faltas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        faltas.setText("Faltas: ");
        getContentPane().add(faltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 290, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Faltas: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 64, -1));

        jButton1.setText("Presenças");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, 180, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Aniversário:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        niver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        niver.setText("niver");
        getContentPane().add(niver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, -1));

        jButton2.setText("Alterar Dados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 630, 180, 30));

        responsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        responsavel.setText("Nome Responsável:");
        getContentPane().add(responsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 290, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        endereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endereco.setText("Endereço:");
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 290, -1));

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("Email:");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 290, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nome Responsável:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        bairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bairro.setText("Bairro:");
        getContentPane().add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 290, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Logradouro:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Bairro:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("CEP:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, -1, -1));

        CEP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CEP.setText("CEP:");
        getContentPane().add(CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 290, -1));

        escola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        escola.setText("Escola:");
        getContentPane().add(escola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 290, -1));

        observacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        observacao.setText("Observação");
        getContentPane().add(observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 290, -1));

        calcado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calcado.setText("Tamanho Calçado:");
        getContentPane().add(calcado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 290, -1));

        roupa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roupa.setText("Tamanho da Roupa:");
        getContentPane().add(roupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 290, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Tamanho da Roupa:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 168, -1));

        faixa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        faixa.setText("Faixa:");
        getContentPane().add(faixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 290, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Tamanho do Calçado:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 180, -1));

        categora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categora.setText("Categoria:");
        getContentPane().add(categora, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 290, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Categoria:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Grau:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 50, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Faixa:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 60, -1));

        grau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grau.setText("Grau:");
        getContentPane().add(grau, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 290, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Escola:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        medicamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        medicamento.setText("Medicamento Contínuo?");
        getContentPane().add(medicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 290, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Medicamento Contínuo?");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Observação");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Autorização de Imagem:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Permissão para Treinar:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Permissão para Competir:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        treinar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        treinar.setText("jLabel2");
        getContentPane().add(treinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, -1, 30));

        competir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        competir.setText("jLabel2");
        getContentPane().add(competir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, 30));

        imagear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imagear.setText("jLabel2");
        getContentPane().add(imagear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, -1, 30));

        ativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ativo.setText("Ativo?");
        getContentPane().add(ativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 64, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Ativo?");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 64, -1));

        jButton3.setText("Adicionar Presença");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 180, 30));

        dias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dias.setText("Dias que Treina:");
        dias.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 330, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Dias de Treino:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 140, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 960, 20));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 20, 680));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 20, 680));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 20, 680));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 20, 680));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 320, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Aluno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Contato");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 170, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Treino");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Endereço");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 110, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 960, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Dados do Aluno");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 340, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Presencas presenca = new Presencas(aluno);
        presenca.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AlterarDados ad = new AlterarDados(aluno, service);
        this.dispose();
        ad.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AdcionarPresença ap = new AdcionarPresença(service, aluno);
        ap.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEP;
    private javax.swing.JLabel ativo;
    private javax.swing.JLabel bairro;
    private javax.swing.JLabel calcado;
    private javax.swing.JLabel categora;
    private javax.swing.JLabel competir;
    private javax.swing.JLabel dias;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JLabel escola;
    private javax.swing.JLabel faixa;
    private javax.swing.JLabel faltas;
    private javax.swing.JLabel grau;
    private javax.swing.JLabel idade;
    private javax.swing.JLabel imagear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel medicamento;
    private javax.swing.JLabel niver;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel observacao;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel responsavel;
    private javax.swing.JLabel roupa;
    private javax.swing.JLabel telefone;
    private javax.swing.JLabel treinar;
    // End of variables declaration//GEN-END:variables
}
