/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacadstro2.telas;

import java.time.DayOfWeek;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import sistemacadstro2.TelaPrincipal;
import sistemacadstro2.entities.Aluno;
import sistemacadstro2.services.Servico;

/**
 *
 * @author lucas
 */
public class TelaCadastro extends javax.swing.JFrame {

    Servico service;
    ArrayList lista;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro(Servico service) {
        initComponents();
        this.service = service;
        textGrau.setText("0");
        textPeso.setText("0");

        segunda.setSelected(true);
        terca.setSelected(true);
        quarta.setSelected(true);
        quinta.setSelected(true);
        sexta.setSelected(true);
    }

    private TelaCadastro() {

    }

    public String verificarTextoVazio(String string) {
        if (string.equals("")) {
            return " ";
        } else {
            return string;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        textPeso = new javax.swing.JTextField();
        textData = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textResponsavel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textCep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textEscola = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textRoupa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textCalcado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textFaixa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textGrau = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textMedicamento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textObservacao = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        checkTreinar = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        checkCompetir = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        checkImagem = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        textCategoria = new javax.swing.JTextField();
        segunda = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        terca = new javax.swing.JCheckBox();
        quarta = new javax.swing.JCheckBox();
        quinta = new javax.swing.JCheckBox();
        sexta = new javax.swing.JCheckBox();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Peso:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Data de aniversário:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, -1));
        getContentPane().add(textTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 181, -1));
        getContentPane().add(textPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        textData.setToolTipText("dd/MM/yyyy");
        textData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataActionPerformed(evt);
            }
        });
        getContentPane().add(textData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 180, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("(dia/mês/ano)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nome Responsável:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));
        getContentPane().add(textResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 270, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 270, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Logradouro:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));
        getContentPane().add(textEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 270, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Bairro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));
        getContentPane().add(textBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 270, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("CEP:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, -1, -1));
        getContentPane().add(textCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 180, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Escola:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        getContentPane().add(textEscola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Tamanho da Roupa:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));
        getContentPane().add(textRoupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 180, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Tamanho do Calçado:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));
        getContentPane().add(textCalcado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 180, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Faixa:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));
        getContentPane().add(textFaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 180, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Grau:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));
        getContentPane().add(textGrau, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 180, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Medicamento Contínuo?");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        getContentPane().add(textMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 270, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Observação?");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));
        getContentPane().add(textObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 270, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Permissão para Treinar:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));
        getContentPane().add(checkTreinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Permissão para Competir:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));
        getContentPane().add(checkCompetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Autorização de Imagem:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));
        getContentPane().add(checkImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Categoria:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));
        getContentPane().add(textCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 180, -1));

        segunda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        segunda.setText("Segunda");
        getContentPane().add(segunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Dias de Treino");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        terca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        terca.setText("Terça");
        getContentPane().add(terca, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, -1, -1));

        quarta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quarta.setText("Quarta");
        getContentPane().add(quarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        quinta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quinta.setText("Quinta");
        getContentPane().add(quinta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        sexta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sexta.setText("Sexta");
        getContentPane().add(sexta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, -1, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 960, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 20, 680));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 20, 680));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 20, 680));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 320, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 960, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 20, 680));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setText("Aluno");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("Contato");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 90, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setText("Endereço");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 110, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setText("Treino");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 90, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Cadastro de Aluno");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 340, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lista = service.read();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try {
            LocalDate teste = LocalDate.parse(textData.getText(), fmt);
            Integer id;
            if (lista.size() == 0 || lista == null) {
                id = 1;
            } else {
                Aluno referencia = (Aluno) lista.getLast();
                id = referencia.getId() + 1;
            }

            if (textName.getText().equals("") || textData.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite um Nome e uma data de Nascimento: ");
            } else if (textPeso.getText().equals("")) {
                JOptionPane.showConfirmDialog(null, "O campo peso não pode estar vazio");
            } else if (textGrau.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "O campo Grau não pode esta vazio");
            } else {
                ArrayList<DayOfWeek> allDays = new ArrayList<>();

                allDays = new ArrayList<>();
                if (segunda.isSelected()) {
                    allDays.add(DayOfWeek.MONDAY);
                }
                if (terca.isSelected()) {
                    allDays.add(DayOfWeek.TUESDAY);
                }
                if (quarta.isSelected()) {
                    allDays.add(DayOfWeek.WEDNESDAY);
                }
                if (quinta.isSelected()) {
                    allDays.add(DayOfWeek.THURSDAY);
                }
                if (sexta.isSelected()) {
                    allDays.add(DayOfWeek.FRIDAY);
                }

                Aluno a1 = new Aluno(textName.getText(), id, verificarTextoVazio(textTelefone.getText()), Double.parseDouble(textPeso.getText()), LocalDate.parse(textData.getText(), fmt), verificarTextoVazio(textResponsavel.getText()), verificarTextoVazio(textEmail.getText()), verificarTextoVazio(textEndereco.getText()), verificarTextoVazio(textBairro.getText()), verificarTextoVazio(textCep.getText()), verificarTextoVazio(textEscola.getText()), verificarTextoVazio(textRoupa.getText()), verificarTextoVazio(textCalcado.getText()), verificarTextoVazio(textCategoria.getText()), verificarTextoVazio(textFaixa.getText()), Integer.parseInt(textGrau.getText()), verificarTextoVazio(textMedicamento.getText()), verificarTextoVazio(textObservacao.getText()), checkTreinar.isSelected(), checkCompetir.isSelected(), checkImagem.isSelected(), allDays);
                lista.add(a1);
                textName.setText("");
                textTelefone.setText("");
                textData.setText("");
                service.atualizarLista(lista);
                
                TelaPrincipal tp = new TelaPrincipal();
                tp.setVisible(true);
                this.dispose();
            }

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Digite a data no formato Adequado: 00/00/0000");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void textDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkCompetir;
    private javax.swing.JCheckBox checkImagem;
    private javax.swing.JCheckBox checkTreinar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JCheckBox quarta;
    private javax.swing.JCheckBox quinta;
    private javax.swing.JCheckBox segunda;
    private javax.swing.JCheckBox sexta;
    private javax.swing.JCheckBox terca;
    private javax.swing.JTextField textBairro;
    private javax.swing.JTextField textCalcado;
    private javax.swing.JTextField textCategoria;
    private javax.swing.JTextField textCep;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textEscola;
    private javax.swing.JTextField textFaixa;
    private javax.swing.JTextField textGrau;
    private javax.swing.JTextField textMedicamento;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textObservacao;
    private javax.swing.JTextField textPeso;
    private javax.swing.JTextField textResponsavel;
    private javax.swing.JTextField textRoupa;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
